// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/rickywei/sparrow/project/api"
)

// Injectors from wire.go:

func WireApp() (*App, error) {
	apiAPI := api.NewApi()
	app, err := NewApp(apiAPI)
	if err != nil {
		return nil, err
	}
	return app, nil
}
