version: "3.0"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    user: ${UID}:${GID}
    volumes:
      - ./volume/log:/app/log
    ports:
      - "8000:80"
    depends_on:
      - mongo
      - redis
      # - prometheus
      # - grafana
    networks:
      - net
    restart: always
    deploy:
      resources:
        limits:
          cpus: "2"

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - .env
    user: ${UID}:${GID}
    volumes:
      - ./volume/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - net
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    user: ${UID}:${GID}
    ports:
      - 6379:6379
    networks:
      - net
    restart: always

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - net
  #   restart: always

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - net
  #   restart: always

networks:
  net:
    driver: bridge
