definitions:
  handler.response-array_po_User:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/po.User'
        type: array
      msg:
        type: string
    type: object
  handler.response-po_User:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/po.User'
      msg:
        type: string
    type: object
  handler.responseWithoutData:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  po.User:
    properties:
      created_at:
        description: create time
        type: integer
      deleted_at:
        description: delete time
        type: integer
      email:
        description: email
        type: string
      id:
        description: id
        type: integer
      mobile:
        description: mobile
        type: string
      nick_name:
        description: nick_name
        type: string
      password:
        description: password
        type: string
      updated_at:
        description: update time
        type: integer
      user_name:
        description: user_name
        type: string
    type: object
  vo.ReqCreateUser:
    properties:
      email:
        type: string
      mobile:
        type: string
      nick_name:
        type: string
      password:
        maxLength: 128
        minLength: 6
        type: string
      user_name:
        type: string
    required:
    - email
    - mobile
    - nick_name
    - password
    - user_name
    type: object
  vo.ReqLogin:
    properties:
      password:
        maxLength: 128
        minLength: 6
        type: string
      user_name:
        type: string
    required:
    - password
    - user_name
    type: object
info:
  contact: {}
paths:
  /api/v1/user:
    post:
      consumes:
      - application/json
      description: create
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.ReqCreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.responseWithoutData'
      tags:
      - user
  /api/v1/user/:id:
    delete:
      consumes:
      - application/json
      description: delete
      parameters:
      - description: ' '
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.responseWithoutData'
      tags:
      - user
    get:
      description: query list
      parameters:
      - description: ' '
        in: query
        name: offset
        required: true
        type: integer
      - description: ' '
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.responseWithoutData'
      tags:
      - user
    put:
      consumes:
      - application/json
      description: update
      parameters:
      - description: ' '
        in: path
        name: id
        required: true
        type: integer
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.ReqCreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.responseWithoutData'
      tags:
      - user
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      description: login
      parameters:
      - description: ' '
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/vo.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.responseWithoutData'
      tags:
      - user
  /api/v1/user/refresh:
    post:
      consumes:
      - application/json
      description: refresh
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.responseWithoutData'
      tags:
      - user
swagger: "2.0"
