// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type Todo struct {
	ID        *string `json:"id,omitempty"`
	CreatedAt *int64  `json:"createdAt,omitempty"`
	UpdatedAt *int64  `json:"updatedAt,omitempty"`
	DeletedAt *int64  `json:"deletedAt,omitempty"`
	UserID    string  `json:"userId"`
	Name      string  `json:"name"`
	Ddl       *int64  `json:"ddl,omitempty"`
	Done      *bool   `json:"done,omitempty"`
	DoneAt    *int64  `json:"doneAt,omitempty"`
}

type TodoInput struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
	Ddl    *int64 `json:"ddl,omitempty"`
	Done   *bool  `json:"done,omitempty"`
	DoneAt *int64 `json:"doneAt,omitempty"`
}

type User struct {
	ID        *string `json:"id,omitempty"`
	CreatedAt *int64  `json:"createdAt,omitempty"`
	UpdatedAt *int64  `json:"updatedAt,omitempty"`
	DeletedAt *int64  `json:"deletedAt,omitempty"`
	Username  string  `json:"username"`
	Nickname  *string `json:"nickname,omitempty"`
	Email     *string `json:"email,omitempty"`
	Password  *string `json:"password,omitempty"`
	Mobile    *string `json:"mobile,omitempty"`
}

type UserInput struct {
	Username string  `json:"username"`
	Nickname *string `json:"nickname,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Mobile   *string `json:"mobile,omitempty"`
}
